server:
  port: 9876
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    showSql: true